behaviors:
  CharacterAI:
    trainer_type: ppo
    hyperparameters:
      batch_size: 32
      buffer_size: 409600
      learning_rate: 0.0001
      beta: 0.01
      epsilon: 0.3
      lambd: 0.95
      num_epoch: 10
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 206
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    #checkpoint_interval: 500000
    max_steps: 10000000
    time_horizon: 32
    summary_freq: 50000
    threaded: true